spring:
    application:
        name: quick-start
    ai:
        deepseek:
            api-key: ${ai_key_ds}
            chat:
                options:
                    model: deepseek-reasoner
        dashscope:
            api-key: ${ai_key_qw}
            chat:
                options:
                    model: qwen3-max
            base-url: https://dashscope.aliyuncs.com
#            base-url: https://dashscope.aliyuncs.com/api/v1

