spring:
    application:
        name: more-platform-and-model
    main:
        allow-bean-definition-overriding: false #是否允许bean覆盖 默认false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${a_aly_ads}:3306/hudistu?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: ${a_mysql_password}
    data:
        redis:
            port: 6379
            host: ${a_aly_ads}
            password: 695847
            database: 1
    ai:
        deepseek:
            api-key: ${ai_key_ds}
            chat:
                options:
                    model: deepseek-reasoner
        dashscope:
            api-key: ${ai_key_qw}
            chat:
                options:
                    model: qwen3-max
            base-url: https://dashscope.aliyuncs.com
#            base-url: https://dashscope.aliyuncs.com/api/v1
        chat:
            memory:
                repository:
                    jdbc:
                        initialize-schema: always
                        schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-mysql.sql
logging:
    level:
        org.springframework.ai.chat.client.advisor: debug


